# Generated by Django 3.0.4 on 2020-04-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rest_api', '0002_auto_20200331_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealhistory',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealhistory',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealhistory',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealhistory',
            name='proteins',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteins',
            field=models.FloatField(default=0),
        ),
    ]
