# Generated by Django 3.0.4 on 2020-03-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fitbit_access_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='fitbit_refresh_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sex',
            field=models.CharField(default='Male', max_length=30),
            preserve_default=False,
        ),
    ]
