# Generated by Django 3.0.4 on 2020-04-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rest_api', '0003_auto_20200414_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='proteins',
            field=models.FloatField(default=0),
        ),
    ]
