# Generated by Django 3.0.5 on 2020-04-22 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rest_api', '0005_auto_20200420_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='client',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='workout_sets',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
