# Generated by Django 3.0.5 on 2020-04-24 07:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api', '0006_auto_20200422_1909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomAdmin',
            new_name='HospitalAdmin',
        ),
    ]
