# Generated by Django 3.0.5 on 2020-05-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_expotoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_high_colesterol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_diabetic',
            field=models.BooleanField(default=False),
        ),
    ]
