name: CI

on:
    push:
        branches: [production]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Create env file
              env:
                  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
                  MONGODB_URL_ATLAS: ${{ secrets.MONGODB_URL_ATLAS }}
              run: |
                  touch .env
                  echo JWT_SECRET_KEY=${JWT_SECRET_KEY} >> .env
                  echo JWT_SECRET_TIME="36000" >> .env
                  echo API_URL="https://unifiles.herokuapp.com/api" >> .env
                  echo MONGODB_URL=${MONGODB_URL_ATLAS} >> .env
                  echo MONGODB_URL_ATLAS=${MONGODB_URL_ATLAS} >> .env
                  cat .env
                  
            - name: Remove _data folder
              run: |
                  rm -r _data

            - name: Commit changes
              run: |
                  git config --global user.name "Vasco Ramos"
                  git add -f .env
                  git commit -a -m "Updates project"
                  
            - name: Add heroku remote origin
              run: git remote add heroku-staging https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      
            - name: Deploy to Heroku
              run: git push heroku-staging production:master -f --no-verify
